### ISSUE TITLE
[HU2] Como usuario quiero poder visualizar el contenido por temas

### ISSUE THREAD

**Issue by Torchu** [DSC-UGR/DSC-website#4]

**Comment by AlexMenor** [comment]
Dev.to tiene etiquetas en los posts. Si nos ponemos un poco de acuerdo en utilizar todos las mismas... ¿Cómo lo veis?

**Comment by cecimerelo** [comment]
Super de acuerdo :+1:

**Comment by andriugarcia** [comment]
Eso funcionaria para Dev.to solamente, para los otros medios no habría temas

**Comment by AlexMenor** [comment]
> Eso funcionaria para Dev.to solamente, para los otros medios no habría temas

¿Vamos a utilizar más medios?

**Comment by andriugarcia** [comment]
Por ahora nos puede servir si vamos a usar Dev.to solamente
